services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Jvelletti\JvDeepltranslatePiflexform\:
    resource: '../Classes/*'

  Jvelletti\JvDeepltranslatePiflexform\Command\TranslateCommand:
    tags:
      - name: 'console.command'
        command: 'jvelletti:translate'
        schedulable: true