services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Jvelletti\JvDeepltranslatePiflexform\:
    resource: '../Classes/*'

  Jvelletti\JvDeepltranslatePiflexform\Command\TranslateCommand:
    tags:
      - name: 'console.command'
        command: 'jvelletti:translate'
        schedulable: true

  Jvelletti\JvDeepltranslatePiflexform\Event\Listener\ConfigToolBarEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'jv-deepltranslate/config'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent

  WebVision\Deepltranslate\Core\Event\Listener\UsageToolBarEventListener: ~